### ISSUE TITLE
using `setDynamicNavigationOptions` to set NavigationOption properties dynamically

### ISSUE THREAD

**Issue by idkjs** [reason-react-native/reason-react-native#585] opened 2019-08-25 21:10 UTC
In the readme for navigation we have the following example:

```reason
open ReactNative;
open Navigation;

[@react.component]
let make = (~navigation, ~screenProps) => {
  <Text> {React.string("Hello world!")} </Text>,
};

make->setDynamicNavigationOptions(params => {
  let navigation = params##navigation;
  let navigationOptions = params##navigationOptions;
  let screenProps = params##screenProps;

// logging results
  Js.log2("DETAIL_PARAMS", params);
  Js.log2("DETAIL_navigationOptions", navigationOptions);
  Js.log2("DETAIL_screenProps", screenProps);

  /* More properties can be set dynamically based on navigation, navigationOptions or screenProps. */
  NavigationOptions.t(~title="Screen 1", ~headerTintColor="red", ());
});

```

I did it like this but this seems not right:

```reason
make->NavigationOptions.setDynamicNavigationOptions(params => {
    let navigation = params##navigation;
    let navigationOptions = params##navigationOptions;
    Js.log2("DETAIL_navigationOptions", navigationOptions);
    // output:
    // DETAIL_navigationOptions Object {
    //   "headerStyle": Object {
    //     "backgroundColor": "#f4511e",
    //   },
    //   "headerTintColor": "#fff",
    //   "headerTitleStyle": Object {
    //     "fontWeight": "bold",
    //   },
    // }
    // identity type switch at top of file: `external unsafeCast: ReactNavigation.NavigationOptions.t => 'a = "%identity";` converts from one type to `'a`:any type which we can then use later to switch colors. This cant be right but it works.
    // have to do identity hack because:
    // ```
    // ReactNavigation.NavigationOptions.t
    // type t
    // <root>/src/OverrideSharedOptionsDemo.re

    // Error: This expression has type
    //          ReactNavigation.NavigationOptions.t =
    //            ReactNavigation.NavigationOptions.t
    //        but an expression was expected of type Js.t('a
    // ```
    // comment out this line to see the error generated
    let navigationOptions = unsafeCast(navigationOptions);
    // Js.log2("DETAIL_navigationOptions", navigationOptions);
    let navigationOptionsheaderTintColor = navigationOptions##headerTintColor;
    let navigationOptionsheaderStylebackgroundColor =
      navigationOptions##headerStyle##backgroundColor;
    // this should be the same as the old headerStyle bg color
    let newHeaderTintColor = navigationOptionsheaderStylebackgroundColor;
    // let oldHeaderStyle = navigationOptions##headerStyle;
    // this should be the same as the old headerTintColor
    let newHeaderStyle: ReactNative.Style.t =
      Style.(style(~backgroundColor=navigationOptionsheaderTintColor, ()));

    let title =
      navigation->Navigation.getParamWithDefault(
        "otherParam",
        "A Nested Details Screen",
      );
    // pass new values to NavigationOptions
    NavigationOptions.t(
      ~title,
      ~headerStyle=newHeaderStyle,
      ~headerTintColor=newHeaderTintColor,
      (),
    );
  });
```

**Comment by cknitt** [comment] 2019-08-29 14:45
The issue is that `NavigationOptions.re` is somewhat incomplete as no accessor functions are defined.

If you had accessor functions, you could do

```reason
let navigationOptions = params##navigationOptions;
let headerTintColor = navigationOptions->NavigationOptions.headerTintColor;
// etc.
```

I think I was previously using `[@bs.deriving abstract]` here which gives you accessor functions in addition to the creation function for the type, but the problem with `[@bs.deriving abstract]` is that you can't use `[@bs.string]` for the "enum" fields.

We should probably add accessor functions, but then how do we handle the "enum" fields there?

/cc @MoOx

**Comment by idkjs** [comment] 2019-08-29 15:50
Ok. I guess we will get to it. Do you know where the docs are for `[@bs.inline]`? Its being used in the repo but I cant find docs for it.

**Comment by idkjs** [comment] 2019-08-30 01:27
@cknitt @MoOx Is there an example of an `accessor` in this repo or anywhere that you could point me to that conforms with what we are trying to do here? Thanks.

**Comment by cknitt** [comment] 2019-09-01 07:21
@idkjs For an accessor, you would use `bs.get`/`bs.set`.

E.g. for the `headerTintColor` from my example:

```reason
// NavigationOptions.re

type t;

// ...

[@bs.get] external headerTintColor: t => Color.t = "headerTintColor";
```

**Comment by MoOx** [comment] 2020-11-08 16:53
Closing as I don't see what we can do in this repo.

**Closed by MoOx** 2020-11-08 16:53 UTC
